# Generated by Django 5.1.3 on 2024-12-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('cliente', models.CharField(max_length=100)),
                ('servico', models.CharField(choices=[('Ajuste de Vestido', 'Ajuste de Vestido'), ('Costura', 'Costura'), ('Conserto', 'Conserto'), ('Outro', 'Outro')], max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=50)),
            ],
        ),
    ]
